### ISSUE TITLE
Add installation tutorials to Arch linux user on README.md

### ISSUE THREAD

**Issue by mohamad-supangat** [WillPower3309/swayfx#108]
- **Description:**
Now at Archlinux, you can easily install SWAYFX from AUR https://aur.archlinux.org/packages/swayfx
Or also from the Repository of Comunity Chaotic-Aur https://github.com/chaotic-aur/packages/issues/2124

Can you give installation guide to another arch linux user on README.md

**Comment by WillPower3309** [comment]
We won't have a guide for every distro, as in each case it's simply install through your package manager. That said, with #103, it will be more clear which distros SwayFX is packaged for!
