### ISSUE TITLE
Shadow damage tracking optimization 

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#116]
We can optimize shadow damage tracking by only damaging areas that the shadows will be visible in. This would mean that if a shadows width exceeds that of the window width + the gaps, we would only damage track the window width + gaps as the shadow wouldn't be visible behind any neighbouring windows.

**Comment by head-gardener** [comment]
I can't quite figure out a way of doing this without shadows appearing cut off.
If we just limit shadows between containers to inner gaps visible separation lines may appear along corresponding borders:
![IMG_20230305_170336_665](https://user-images.githubusercontent.com/49650767/222965714-a68d4bcf-eaf8-4a64-b020-da009193b72c.jpg)
Effect may be hard to see on the compressed image above, but a darker rectangle is extending below the gap.

**Comment by ErikReider** [comment]
> I can't quite figure out a way of doing this without shadows appearing cut off. If we just limit shadows between containers to inner gaps visible separation lines may appear along corresponding borders: ![IMG_20230305_170336_665](https://user-images.githubusercontent.com/49650767/222965714-a68d4bcf-eaf8-4a64-b020-da009193b72c.jpg) Effect may be hard to see on the compressed image above, but a darker rectangle is extending below the gap.

Do you have code available to test? >:)

**Comment by head-gardener** [comment]
> Do you have code available to test? >:)

Sure, though I have slightly modified the shader to make the effect more apparent. Should I open a PR?

**Comment by ErikReider** [comment]
> > Do you have code available to test? >:)
> 
> Sure, though I have slightly modified the shader to make the effect more apparent. Should I open a PR?

Sure :)

**Comment by ErikReider** [comment]
Wouldn't this look weird? Just cutting the shadow off would not look very natural. I'd actually be against adding this.

![image](https://user-images.githubusercontent.com/35975961/222968343-2f96a9ce-1bcf-490a-abc2-f6af5ac39d47.png)

What do you think @WillPower3309?

**Comment by WillPower3309** [comment]
Hmm, yeah I'm realizing maybe this isn't the best idea:/ in my head I didn't even think of that, was focused on optimizing rendering as much as possible!
