### ISSUE TITLE
No shadows on a specific app 

### ISSUE THREAD

**Issue by Iss-in** [WillPower3309/swayfx#118]
swayfx-git r6947.4222b98a-1
wlroots 0.16.2-1

So im using a sticky note app , https://github.com/linuxmint/sticky
somehow this is the only gui app for which shadows arent shown, only window rule ive for this app is floating enable 

round corners are show tho

**Comment by ErikReider** [comment]
Shadows aren't shown by default for windows with CSD (windows that draw their own decorations). There's an experimental config option to enable shadows for csd windows. 

`shadows_on_csd on` if my memory serves me right
