### ISSUE TITLE
Older sway bug with easy fix 

### ISSUE THREAD

**Issue by kevinclevenger** [WillPower3309/swayfx#122]
Is there any possibility of fixing this sway bug in swayfx? Minor issue but pretty annoying given the right circumstance.
[Cycling through floating windows on the same workspace does not wrap](https://github.com/swaywm/sway/issues/6845)

1. Start three terminal windows
2. Toggle floating on all three (all align to the center of the screen)
3. $mod-h/l will cycle through the floating windows and wrap both ways
4. Move two of the floating windows
5. $mod-h/l will cycle through the floating windows once and stop, it will not wrap back to the first/last window

In [C#3](https://github.com/swaywm/sway/issues/6845#issuecomment-1454754988) Ristovski mentions:
focus_wrapping is only used in node_get_in_direction_tiling, not in node_get_in_direction_floating. So this is missing functionality

**Comment by head-gardener** [comment]
I think this issue should be left to sway maintainers to resolve.
