### ISSUE TITLE
Duplicate session_lock logic in render.c

### ISSUE THREAD

**Issue by ErikReider** [WillPower3309/swayfx#123]
https://github.com/WillPower3309/swayfx/blob/ac31a612164828ca6ae5478332eee3cd2317ffdc/sway/desktop/render.c#L1413-L1481

**Comment by WillPower3309** [comment]
Good catch. Is this upstream?

**Comment by WillPower3309** [comment]
Upstream: https://github.com/swaywm/sway/blob/master/sway/desktop/render.c#L1065-L1098

**Comment by WillPower3309** [comment]
> Upstream: https://github.com/swaywm/sway/blob/master/sway/desktop/render.c#L1065-L1098

I think based on this we're okay, looks the same to me?

**Comment by ErikReider** [comment]
Yeah but it's duplicated in swayfx

**Comment by ErikReider** [comment]
Updated the permalink

**Comment by WillPower3309** [comment]
done in https://github.com/WillPower3309/swayfx/commit/9a0d2899a24d75ca1bebade49f155c5f12a5128f
