### ISSUE TITLE
Black Bar on Fullscreen Windows

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#129]
https://github.com/WillPower3309/swayfx/commit/8f8a5c0492e07de80f874c9741ee904b864e25b2 caused an issue where a Fullscreen window being focused exhibits the following behavior:
https://user-images.githubusercontent.com/13266308/226187703-a6d3b3ab-e544-40de-98d2-5abd7ee5fa5a.mp4

**Comment by ErikReider** [comment]
Hmm. GTK4 applications fullscreen like normal while GTK3, QT, and Wine applications don't. I wonder if it has to do with GTK4 CSD?

On my setup, the black outline doesn't disappear on focus change which is strange I guess?
