### ISSUE TITLE
Clipped window with smart edge borders on

### ISSUE THREAD

**Issue by natsukagami** [WillPower3309/swayfx#135]
### Please read the following before submitting:
- [x] Proprietary graphics drivers, including nvidia, are not supported. Please use the open source equivalents, such as nouveau, if you would like to use Sway.
- [x] Please do NOT submit issues for information from the github wiki. The github wiki is community maintained and therefore may contain outdated information, scripts that don't work or obsolete workarounds.
  If you fix a script or find outdated information, don't hesitate to adjust the wiki page.

### Please fill out the following:
- **Swayfx Version:**
  - `sway -v`: `sway version 0.2`. Specifically, I'm using latest master commit's ([7d5d7a3](https://github.com/WillPower3309/swayfx/commit/7d5d7a3022eb17835cea7af7290b1a5d2fe4b03a)) nix flake, with nixpkgs overriden to latest nixpkgs-unstable (nixOS/nixpkgs@c9ece0059f42e0ab53ac870104ca4049df41b133) commit (so base sway is 1.8.1).

- **Debug Log:** will do in a bit.

- **Configuration File:**
minimal config is just the default with `hide_edge_borders smart`.

With `hide_edge_borders` `none` and `smart`:
![with hide_edge_borders none](https://media.discordapp.net/attachments/1045402900370837567/1088432786001645720/image.png?width=1236&height=681)
![with hide_edge_borders smart](https://media.discordapp.net/attachments/1045402900370837567/1088432786446221362/image.png?width=1238&height=681)

**Comment by ErikReider** [comment]
Seems like we're not checking if some of the borders should be hidden or not.
https://github.com/WillPower3309/swayfx/blob/50e2422e743c0b337097dd2367f82e0d4b20fabc/sway/desktop/render.c#L659-L665

This becomes more complicated when we only hide ex horizonal borders... How should we handle rounded corners if we only show horizontal borders?
![image](https://user-images.githubusercontent.com/35975961/233840680-d919e8c6-cca9-4463-8daf-664dffc2e46b.png)

**Comment by WillPower3309** [comment]
> Seems like we're not checking if some of the borders should be hidden or not.
> https://github.com/WillPower3309/swayfx/blob/50e2422e743c0b337097dd2367f82e0d4b20fabc/sway/desktop/render.c#L659-L665
> 
> This becomes more complicated when we only hide ex horizonal borders... How should we handle rounded corners if we only show horizontal borders? How does [i3-gaps-rounded](https://github.com/jbenden/i3-gaps-rounded) handle this? 🤔
> ![image](https://user-images.githubusercontent.com/35975961/233840680-d919e8c6-cca9-4463-8daf-664dffc2e46b.png)

Actually not sure if i3-gaps-rounded has rounded borders, I'll take a peek. This would be easier with the border refactor :/ we should think about what we wanna do here. Perhaps we don't support the option on 0.3 and try to support it with the border rework in 1.0

**Comment by ErikReider** [comment]
> Perhaps we don't support the option on 0.3 and try to support it with the border rework in 1.0

Yeah, the border rework will make it easier to do stuff like this:

![image](https://user-images.githubusercontent.com/35975961/233850285-163a2b25-64b3-47fd-ab42-eae72277cd8d.png)

**Comment by WillPower3309** [comment]
> > Perhaps we don't support the option on 0.3 and try to support it with the border rework in 1.0
> 
> Yeah, the border rework will make it easier to do stuff like this:
> 
> ![image](https://user-images.githubusercontent.com/35975961/233850285-163a2b25-64b3-47fd-ab42-eae72277cd8d.png)
> 

Exactly! Let's push this to 1.0

**Comment by dev-forty-two** [comment]
The same problem happens with `hide_edge_borders` set to `both`. Perhaps add checks for this add well.
