### ISSUE TITLE
SwayFX not building on fedora 38

### ISSUE THREAD

**Issue by Bcez** [WillPower3309/swayfx#140]
Branch is not building and it is saying that json-c is not installed when it is installed.
OS : Fedora 38 Preview

`The Meson build system
Version: 1.0.1
Source dir: /home/eric/Downloads/swayfx-blur
Build dir: /home/eric/Downloads/swayfx-blur/build
Build type: native build
Project name: sway
Project version: 0.2
C compiler for the host machine: cc (gcc 13.0.1 "cc (GCC) 13.0.1 20230318 (Red Hat 13.0.1-0)")
C linker for the host machine: cc ld.bfd 2.39-9
Host machine cpu family: x86_64
Host machine cpu: x86_64
Neither a subproject directory nor a wlroots.wrap file was found.
Subproject  wlroots is buildable: NO (disabling)
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Found CMake: /usr/bin/cmake (3.26.2)
Run-time dependency json-c found: NO (tried pkgconfig and cmake)

meson.build:47:0: ERROR: Dependency "json-c" not found, tried pkgconfig and cmake

A full log can be found at /home/eric/Downloads/swayfx-blur/build/meson-logs/meson-log.txt
WARNING: Running the setup command as meson [options] instead of meson setup [options] is ambiguous and deprecated.`

**Comment by WillPower3309** [comment]
Which version of json-c do you have installed?

**Comment by ErikReider** [comment]
You'll need the -devel packages (`json-c-devel`, `cairo-devel`, `gdk-pixbuf2-devel`, etc...)

**Comment by Bcez** [comment]
build works now but blur is not working and it is giving me a error saying blur command does not exist

**Comment by head-gardener** [comment]
Currently blur is only available on `blur` branch.
