### ISSUE TITLE
Shadows being clipped on some windows

### ISSUE THREAD

**Issue by ErikReider** [WillPower3309/swayfx#141]
![image](https://user-images.githubusercontent.com/35975961/231776473-defb9ae4-cabf-4639-896f-62a09ffb1811.png)

Happens with Discords small starting window (the one that downloads updates etc) and swappy (screenshot editing GUI). This only occurs on my left 1080p monitor for some reason and not my 1440p monitor

**Comment by RicArch97** [comment]
Similar issue here:

![2023-04-16T00:26:24,703497419+02:00](https://user-images.githubusercontent.com/61013287/232263644-a5fb3027-765c-4353-a214-6ea1f5e0cd62.png)

Details:
* Only happens on my right monitor (might be because it's ultrawide so more width than my 16:9 left monitor)
* Happens when the width of the widow exceeds a certain boundary
* Happens on all types of applications (not just GTK)

Short video:

https://user-images.githubusercontent.com/61013287/232263800-8b51a0ae-aab2-441b-ba84-886dd69687a6.mp4

Output of `swaymsg -t get_outputs`:
```
Output DP-1 'LG Electronics LG ULTRAGEAR 103NTDV9C874' (focused)
  Current mode: 3440x1440 @ 160.000 Hz
  Position: 2560,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: 2 ms
  Adaptive sync: enabled
  Available modes:
    3440x1440 @ 143.923 Hz
    3440x1440 @ 60.001 Hz
    3440x1440 @ 160.000 Hz
    ...

Output DP-2 'LG Electronics LG ULTRAGEAR 206MARZAD334'
  Current mode: 2560x1440 @ 164.958 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 11
  Max render time: 2 ms
  Adaptive sync: enabled
  Available modes:
    2560x1440 @ 164.958 Hz
    2560x1440 @ 143.973 Hz
    2560x1440 @ 119.998 Hz
    ...
```

**Comment by WillPower3309** [comment]
Important to note that they're clipped right after the corners of rounded windows. We should test if this is present with `corner_radius` set to 0

**Comment by ErikReider** [comment]
> Important to note that they're clipped right after the corners of rounded windows. We should test if this is present with `corner_radius` set to 0

Yeah, still an issue. One consistent applications that shows this is Sequeler with it's properties window open:
![image](https://user-images.githubusercontent.com/35975961/232615602-4458caaf-6fcd-44d7-b9aa-10dde95150d4.png)

**Comment by WillPower3309** [comment]
Looks like it doesn't bend around the corner though, so a bit of different behavior there at least

**Comment by WillPower3309** [comment]
Hmm for @RicArch97 it appears like it happens when part of the window overlaps onto to his other monitor

**Comment by RicArch97** [comment]
> Hmm for @RicArch97 it appears like it happens when part of the window overlaps onto his other monitor. Also seems to be floating windows only for both of you?

Not necessarily, it also happens when the window doesn't overlap into my other monitor. It's also not just floating windows, happens on tiling onces as well. Captured some data from `swaymsg -t get_tree | jq` for a window right after it exceeds the width where it starts happening;
```
"rect": {
  "x": 2966,
  "y": 241,
  "width": 2561,
  "height": 1006
 },
"deco_rect": {
  "x": 321,
  "y": 195,
  "width": 2561,
  "height": 31
},
"window_rect": {
  "x": 1,
  "y": 0,
  "width": 2559,
  "height": 1005
},
"geometry": {
  "x": 0,
  "y": 0,
  "width": 800,
  "height": 600
},
```
