### ISSUE TITLE
Make Rounded Corners Anti-aliased

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#16]
- **Description:**
The rounded corners should be anti-aliased! Right now, they seem a little jagged:
![2022-08-21_17-08-1661118083](https://user-images.githubusercontent.com/13266308/185812086-ddcd4c1d-3b8d-4e59-bfee-0e71dd868b3e.jpg)

**Comment by ErikReider** [comment]
Hmmm. Seems like Webcord, Discord, Spotify do not work. I'll test the main branch and see if it's reproducible there
