### ISSUE TITLE
Artifacts when a floating window goes over a layer with effects enabled

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#165]
If you make a window float, then drag it onto waybar, you can see the artifacts in the first image. if you deselect the window (click on wallpaper for example), the artifacts disappear.

![2023-05-23_21-05-1684893397](https://github.com/WillPower3309/swayfx/assets/13266308/a9a8b536-4ace-4838-bd6a-98cf6047b8b2)

![2023-05-23_21-05-1684893408](https://github.com/WillPower3309/swayfx/assets/13266308/267c61d5-76ff-4674-9a8f-85dbc2eb66d4)

**Comment by ErikReider** [comment]
https://github.com/WillPower3309/swayfx/blob/6402611e5a472e08e2212fecc286020f991de4da/sway/config.c#L1097-L1099

Is the cause. It underestimates the blur size.

Wayfire uses this but it is a bit overkill:

```c
pow(2, config->blur_params.num_passes + 1) * config->blur_params.radius
```

**Comment by ErikReider** [comment]
Nvm, found the bug. We destroy the main buffer on render end which gives the blur less data to work with (everything outside of the damage is black).

I'll post a PR soon ish
