### ISSUE TITLE
[copr] Add rawhide target

### ISSUE THREAD

**Issue by mochaaP** [WillPower3309/swayfx#166]
The package should build without problem on `rawhide`. You could also enable auto branching with this approach. :)

<https://copr.fedorainfracloud.org/coprs/swayfx/swayfx/>

**Comment by ErikReider** [comment]
Should just be two toggles that need to be pressed :)

**Comment by mochaaP** [comment]
thanks! just remember to rebuild otherwise I couldn't get a package XD
