### ISSUE TITLE
`smart_borders off` makes transparent border instead of hiding

### ISSUE THREAD

**Issue by EvysGarden** [WillPower3309/swayfx#167]
## system info
```
OS: Arch Linux
Kernel; Linux zen 6.3.3-zen1-1-zen
CPU: AND Ryzen 7 5700U
GPU: Integrated radeon graphics
```

## issue
when `smart_borders on` is set in config, a transparent border is seen instead of none when on a workspace with a single tiling window.

![image](https://github.com/WillPower3309/swayfx/assets/92547295/53f0f069-7cc1-47d1-8816-4be686e8fddb)

## does not happen on sway
on sway this issue is not present and it looks like the following
![image](https://github.com/WillPower3309/swayfx/assets/92547295/74857c89-2f7f-4d00-b7ff-5646b3a789a9)

**Comment by lepz0r** [comment]
duplicate of this? #135

**Comment by EvysGarden** [comment]
hmm, seems so
