### ISSUE TITLE
Can't build from master or 0.3 in voidlinux.

### ISSUE THREAD

**Issue by moilong** [WillPower3309/swayfx#170]
`void@mnbvcxz ~/D/swayfx-0.3> ninja -C build
ninja: Entering directory `build'
[77/334] Compiling C object sway/sway.p/lock.c.o
FAILED: sway/sway.p/lock.c.o 
cc -Isway/sway.p -Isway -I../sway -Iinclude -I../include -Isway/desktop/fx_renderer/shaders -Iprotocols -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libdrm -I/usr/include/json-c -I/usr/include/libevdev-1.0/ -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/elogind -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O0 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-unused-result -Wno-missing-braces -Wundef -Wvla '-DSYSCONFDIR="//usr/local/etc"' '-DSWAY_VERSION="0.3"' -fmacro-prefix-map=../= -pthread -MD -MQ sway/sway.p/lock.c.o -MF sway/sway.p/lock.c.o.d -o sway/sway.p/lock.c.o -c ../sway/lock.c
../sway/lock.c: In function 'handle_new_surface':
../sway/lock.c:120:50: error: 'struct <anonymous>' has no member named 'mode'
  120 |         wl_signal_add(&output->wlr_output->events.mode, &surf->output_mode);
      |                                                  ^
[79/334] Compiling C object sway/sway.p/main.c.o
ninja: build stopped: subcommand failed.`

Can build sway master though.

**Comment by ErikReider** [comment]
You need wlroots stable

**Comment by moilong** [comment]
Ok.
