### ISSUE TITLE
Sway window decorations can be hidden/cropped when blur is enabled

### ISSUE THREAD

**Issue by the-blank-x** [WillPower3309/swayfx#174]
- **Swayfx Version:** sway version 0.3-6acc283 (May 25 2023, branch 'master')
- **Debug Log:** [swayfx.log](https://github.com/WillPower3309/swayfx/files/11581048/swayfx.log)
- **Configuration File:** [sway.tar.gz](https://github.com/WillPower3309/swayfx/files/11581052/sway.tar.gz) (the default configuration file but with `blur enabled` at the end)
- **Description:**
  If `blur enabled` is specified in the config file, sway's window decorations are hidden/cropped when a window that draws its own window decorations client-side is tabbed. I cannot reproduce it if `blur enabled` is set during runtime, nor can I reproduce it with upstream sway version 1.8.1
- **Steps to reproduce:**
  Add `blur enabled` to the end of your sway config file and reload/restart/start sway, and either:
  - Open [baobab](https://wiki.gnome.org/Apps/DiskUsageAnalyzer), and make it tabbed (if the window decoration is still fully there, open its About window, then unfloat and tab it)
  - Open [czkawka](https://github.com/qarmin/czkawka), and make it tabbed
- **Screenshots:**
  ![](https://github.com/WillPower3309/swayfx/assets/45762106/7a00e03c-538b-415b-ab52-07525429d26e)
  ![](https://github.com/WillPower3309/swayfx/assets/45762106/b741080d-850c-434b-830a-cecab7b354eb)

**Comment by ErikReider** [comment]
Strange, the blur should only be the size of the surface...
