### ISSUE TITLE
Get Layer Name

### ISSUE THREAD

**Issue by patrickaldis** [WillPower3309/swayfx#175]
Is there currently a way to get the names of all active layers?

I'm trying to get the layer name for the`dunst` notification daemon

**Comment by famfo** [comment]
The layer name for the notification dameon is `notifications` iirc, you can use `swaymsg -t get_tree` to get all active layers.

**Comment by WillPower3309** [comment]
> The layer name for the notification dameon is `notifications` iirc, you can use `swaymsg -t get_tree` to get all active layers. 

I think I'll add this to the README to prevent any more confusion, I know it isn't at all clear :)

**Comment by ErikReider** [comment]
> I think I'll add this to the README to prevent any more confusion, I know it isn't at all clear :)

Just copy/paste the content from the Man page?

**Comment by WillPower3309** [comment]
> > I think I'll add this to the README to prevent any more confusion, I know it isn't at all clear :)
> 
> Just copy/paste the content from the Man page?

Figure getting layer names could use a section

**Comment by patrickaldis** [comment]
Maybe I'm missing something. But my tree doesn't contain waybar or dunst, I just assumed it didn't show layers

**Comment by ErikReider** [comment]
> Maybe I'm missing something. But my tree doesn't contain waybar or dunst, I just assumed it didn't show layers

Try using `get_outputs` instead

**Comment by patrickaldis** [comment]
> Try using `get_outputs` instead

This shows the connected video outputs and their specs

**Comment by ErikReider** [comment]
> > Try using `get_outputs` instead
> 
> This shows the connected video outputs and their specs

Yeah, `swaymsg -r -t get_outputs` also includes the layer information for each display

**Comment by patrickaldis** [comment]
Ah yeah, that seems to work great. I don't think it's trivial though.

This is the full command I ended up using:

```
swaymsg -r -t get_outputs | jq '.[0].layer_shell_surfaces | .[] | .namespace'
```

Which gives a nice output of:
```
"wallpaper"
"waybar"
"notifications"
```

So @famfo remembers correctly :)

If I get time I'll add it to the docs

**Comment by WillPower3309** [comment]
Added to the README, thanks!
