### ISSUE TITLE
Static workspaces

### ISSUE THREAD

**Issue by 33KK** [WillPower3309/swayfx#176]
### Please fill out the following:
- **Description:**
This would make it possible to switch to a new workspace with mouse or the scroll wheel, or using the `workspace next` command. Also I find it much more visually intuitive to have all workspaces always visible on the bar, as I do not need to parse the number to understand which workspace it is.

I suggest to simply add a command like this:
```
workspace <name> static|persistent yes
```
And create the workspace on config load and NOT destroy it when it is empty.

i3 (https://github.com/i3/i3/issues/1902#issuecomment-138110166) and therefore sway (https://github.com/swaywm/sway/issues/7220 & https://github.com/swaywm/sway/issues/4928#issuecomment-1066073480) refuse to add this for "look & feel" reasons or something, the i3bar-specific ["solution"](https://github.com/i3/i3/pull/4311) implemented by i3 is not implemented by sway (https://github.com/swaywm/sway/issues/7419)

**Comment by ErikReider** [comment]
You can most probably do this through a few simple scripts :)

**Comment by 33KK** [comment]
> You can most probably do this through a few simple scripts :)

Not nearly as convenient and easy, and bar-specific setup necessary, which isn't even possible on swaybar I think

**Comment by WillPower3309** [comment]
Workspaces visible on the bar can be done in waybar: https://github.com/Alexays/Waybar/blob/master/man/waybar-sway-workspaces.5.scd#L63-L67

**Comment by 33KK** [comment]
I have actually implemented this already, trying to get it merged into upstream sway, but it probably will get rejected https://github.com/swaywm/sway/pull/7631
