### ISSUE TITLE
waybar layer_effects issue with shadows

### ISSUE THREAD

**Issue by justinesmithies** [WillPower3309/swayfx#189]
I'm using `sway version 0.3.1` and when waybar is running with the following setting `layer_effects waybar blur enable; shadows enable; corner_radius 3` as default if I toggle waybar using my this keybind `bindsym $mod+x exec killall -SIGUSR1 waybar`  the bar toggles as expected but when it is gone it leaves a partially transparent waybar shape behind which only disappears once it's toggled back on again.

**Comment by ErikReider** [comment]
Could you provide a recording/screenshot? :)

**Comment by justinesmithies** [comment]
![2023-06-14_13-06-1686746368](https://github.com/WillPower3309/swayfx/assets/1571498/a4ff7db6-600a-4c32-8f2e-4d9bec4c98ba)
![2023-06-14_13-06-1686746384](https://github.com/WillPower3309/swayfx/assets/1571498/5c03aa3c-ad24-4669-b6c2-b59f882fddc8)
![2023-06-14_13-06-1686746397](https://github.com/WillPower3309/swayfx/assets/1571498/3f63de59-200b-4520-964a-ba6f670bd546)
![2023-06-14_13-06-1686746407](https://github.com/WillPower3309/swayfx/assets/1571498/9602b7b3-710c-4e1b-b469-997209188988)

**Comment by RAR27** [comment]
I assume its because the bar is still there technically, just disabled and transparent? If so, if we had something like #159 but for shadows, that would probably fix it.

**Comment by ErikReider** [comment]
I wonder why the they are setting the opacity to 0 on the Waybar window instead of just hiding and showing the window? This might be a waybar issue

**Comment by justinesmithies** [comment]
> I wonder why the they are setting the opacity to 0 on the Waybar window instead of just hiding and showing the window? This might be a waybar issue

Could it be a Waybar issue even though when I disable shadows for the waybar layer_effects it works ok ??
Also the same waybar config with the same keybinding to toggle it works on swaywm and hyprland.

**Comment by ErikReider** [comment]
> > I wonder why the they are setting the opacity to 0 on the Waybar window instead of just hiding and showing the window? This might be a waybar issue
> 
> Could it be a Waybar issue even though when I disable shadows for the waybar layer_effects it works ok ?? Also the same waybar config with the same keybinding to toggle it works on swaywm and hyprland.

They should hide the window instead of just lowering the window behind everything and setting the opacity to 0. The window is still there so Sway can't really tell the difference. They should hide the window properly

**Comment by emanuelserpa** [comment]
Looks like the same problem with mako.

![image](https://github.com/WillPower3309/swayfx/assets/934124/50871a40-a587-4742-8d53-52228e001136)

**Comment by ErikReider** [comment]
Closing due to it being a Waybar issue
