### ISSUE TITLE
blur not working without dim (i3blocks-swaybar)

### ISSUE THREAD

**Issue by frogiraffe** [WillPower3309/swayfx#195]
### minimal config
```
blur enable
blur_passes 1
blur_radius 3
layer_effects "panel" "blur enable"
default_dim_inactive 0.05
dim_inactive_colors.unfocused #000000D9
output * bg "$wallpaper-path" fill

bar {
    position top

    status_command i3blocks

    colors {
        statusline #ffffff
        background #1e1e2eAA
    }
}

```
**how to reproduce**
use i3blocks or swaybar, and if u remove the lines for dimming and the color of it, the blur layer_effect for the panel wont work. when i use the dimming it somehow just works.

**Comment by ErikReider** [comment]
This seems to be a swaybar issue and shoud be fixed in sway-git https://github.com/swaywm/sway/pull/7527

We'll rebase onto the latest sway release when they release the next version (1.9) :)
