### ISSUE TITLE
Using any kind of split on a floating transparent window causes xray to be enabled

### ISSUE THREAD

**Issue by LeadSeason** [WillPower3309/swayfx#207]
### Please read the following before submitting:
- Proprietary graphics drivers, including nvidia, are not supported. Please use the open source equivalents, such as nouveau, if you would like to use Sway.
- Please do NOT submit issues for information from the github wiki. The github wiki is community maintained and therefore may contain outdated information, scripts that don't work or obsolete workarounds.
  If you fix a script or find outdated information, don't hesitate to adjust the wiki page.

### Please fill out the following:
- **Swayfx Version:**
  - `sway version 0.3.2-c7fa46fa (Jul 23 2023, branch 'master')`

- **Debug Log:**
  - [sway.log](https://gist.github.com/LeadSeason/31d61f758f8b64d29379e9a38d81dd8b)
  - It took me some time, so might be a bit longer.

- **Configuration File:**
  - [config](https://gist.github.com/LeadSeason/5cd27f11d9218b4d93f094f905eb075e)
  - Only different's is blur is enable.
  - Mod is changed because my super key doesn't work 😥
 ```diff
 diff --git a/config b/etc/sway/config
index 3aa7a88..401c02d 100644
--- a/config
+++ b/etc/sway/config
@@ -25,7 +25,7 @@ set $menu dmenu_path | dmenu | xargs swaymsg exec --
 corner_radius 10
 
 # Window background blur
-blur on
+blur off
 blur_xray off
 blur_passes 2
 blur_radius 5
```

- **Description:**
Using any kind of split on a floating transparent window causes xray to be enabled
#### Steps to reproduce
Have a terminal setup for transparency 
```
swaymsg exec obs
swaymsg exec kitty
swaymsg floating true
swaymsg split v
```
observe results
Example video is not using the default configs, here are the [dotfiles](https://github.com/LeadSeason/dotfiles/blob/af1f5e20b41f1c9206e220e8400eabed9140f3b0/.config/sway/config)  
issue still happens on defaults with `blur on`.

https://github.com/WillPower3309/swayfx/assets/60569772/68ebf23f-e3d5-41cc-a3e9-216231af9d3a

**Comment by ErikReider** [comment]
Can reproduce. Strange... Will look into it when I have time :)

**Comment by LeadSeason** [comment]
This happens on the latest version `sway version 0.3.2-7c75b219 (Nov 30 2023, branch 'master')`
![image](https://github.com/WillPower3309/swayfx/assets/60569772/5757e8fb-097c-41c2-983c-33460f91bee9)

https://github.com/WillPower3309/swayfx/assets/60569772/eaa321cd-001b-4900-88e6-1f467fdf55e8

**Comment by ErikReider** [comment]
Seems like d89c365 overwrote the fix... I'll post a quick PR addressing this 😅
