### ISSUE TITLE
NixOS: env XDG_CURRENT_SESSION and XDG_CURRENT_DESKTOP env variables are not set

### ISSUE THREAD

**Issue by aacebedo** [WillPower3309/swayfx#215]
- **Swayfx Version:**
  - 0.3.2

- **Debug Log:**
N/A

- **Configuration File:**
N/A

- **Stack Trace:**
N/A

- **Description:**
When using swayfx, the two XDG_CURRENT_SESSION and XDG_CURRENT_DESKTOP variables are not set during login. This breaks screensharing in wayland. Those two variables are set correctly when using sway on the same machine (I am on NixOS so I only change the package to install without changing the rest.

**Comment by RicArch97** [comment]
Known issue, happens because setting `sway.package = pkgs.swayfx` does not apply the wrapper to that package, it's a limitation in the sway module.

Temporary fix is to create an overlay for `pkgs.sway`, replacing it with swayfx.

**Comment by WillPower3309** [comment]
Related to https://github.com/WillPower3309/swayfx/issues/161

**Comment by aacebedo** [comment]
Thanks for the info! I close this then

**Comment by name-snrl** [comment]
> Temporary fix is to create an overlay for `pkgs.sway`, replacing it with swayfx.

This does not solve the problem. I installed swayfx with `pkgs.sway` override:

```nix
package = with pkgs; sway.override { sway-unwrapped = swayfx; };
```

But there are still problems, e.g. `flameshot` doesn't work if I run it via sway - `sway exec 'flameshot gui -r | wl-copy'`
