### ISSUE TITLE
Clipping issue akin to #135 with `hide_edge_borders` set to `both`

### ISSUE THREAD

**Issue by dev-forty-two** [WillPower3309/swayfx#217]
Although https://github.com/WillPower3309/swayfx/pull/171 fixes the clipping issue reported in #135, when `hide_edge_borders` is set to `none` or `smart`, the problem persists when `hide_edge_borders` is set to `both`.

![screenshot](https://github.com/WillPower3309/swayfx/assets/143287701/01e184b5-b9f7-46d4-a639-f1bfdeb33500)

 Perhaps add checks for this as well.

**Comment by ErikReider** [comment]
Seems to be an issue in sway-git as well, so it's an upstream issue. Please open an issue there :)
