### ISSUE TITLE
Add sway-portals.conf for xdg-desktop-portal >= 1.17

### ISSUE THREAD

**Issue by mochaaP** [WillPower3309/swayfx#226]
See <https://src.fedoraproject.org/rpms/sway/c/30a4f85fedaeebcdcf25dbe4496bd771a777e73e>, otherwise `xdg-desktop-portal` won't register many interfaces.

**Comment by mochaaP** [comment]
cc @WillPower3309 consider rebuilding this in Copr

**Comment by saber-nyan** [comment]
Yup, debugging with [official xdg-desktop-portal-wlr guide](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist) led me here...

What's weird is that on Arch Linux the screen sharing worked for a while, but stopped after the swayfx update.

**Comment by WillPower3309** [comment]
> Yup, debugging with [official xdg-desktop-portal-wlr guide](https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist) led me here...
> 
> What's weird is that on Arch Linux the screen sharing worked for a while, but stopped after the swayfx update.
> 
> Unfortunately, the mochaaP's workaround didn't work for me.

Did you end up finding a fix?

**Comment by WillPower3309** [comment]
Fixed in aur with https://github.com/WillPower3309/swayfx/pull/239

**Comment by dongdigua** [comment]
consider rebuild +1
newbie users (like me) probably don't know that the problem is related to `sway-portals.conf`, so they may not find this issue (
