### ISSUE TITLE
[Bug] Keys like [ ] - = as shortcuts, don't work in sway conf file

### ISSUE THREAD

**Issue by IceAsteroid** [WillPower3309/swayfx#227]
### Please fill out the following:
- **Swayfx Version:**
  sway version 0.3.2

- **Debug Log:**
 	https://pastebin.com/FPhYSbhS

- **Configuration File:**
	https://pastebin.com/TvAfy5i0

**Description**
It's said in a sway issue page, users are able to use keys like "[", and "]" as parts of shortcuts in sway conf file, here: https://github.com/swaywm/sway/issues/5159

But when I specified them in the conf file. SwayFX complained they are "unknown key or buttom"

**Comment by IceAsteroid** [comment]
Like follows:

![screenShot-grim_20231003203643](https://github.com/WillPower3309/swayfx/assets/90975914/80dc49d5-df1f-45fa-9b1a-4b9c53252168)

**Comment by Sonico98** [comment]
> Like follows:
> 
> ![screenShot-grim_20231003203643](https://user-images.githubusercontent.com/90975914/272262748-80dc49d5-df1f-45fa-9b1a-4b9c53252168.jpeg)
> 
> Any ideas?
> 
> Moreover, I also tested "," comma and "." period, they both worked.

In the issue you quoted, they state you should use "bracketleft", but you're writing "braketleft" instead (notice the missing "c" before the "k"). Also, you could use the keycode with bindcode, which is also mentioned in that issue.

**Comment by ErikReider** [comment]
> > Like follows:
> > 
> > ![screenShot-grim_20231003203643](https://user-images.githubusercontent.com/90975914/272262748-80dc49d5-df1f-45fa-9b1a-4b9c53252168.jpeg)
> > 
> > Any ideas?
> > 
> > Moreover, I also tested "," comma and "." period, they both worked.
> 
> In the issue you quoted, they state you should use "bracketleft", but you're writing "braketleft" instead (notice the missing "c" before the "k"). Also, you could use the keycode with bindcode, which is also mentioned in that issue.

Exactly. This isn't a SwayFX specific issue but an upstream Sway issue so I'll be closing this. You should open an issue upstream if the comments here haven't helped :)

**Comment by IceAsteroid** [comment]
@Sonico98 @ErikReider
Sorry guys, that's badly my issue. Which I misspelled the word, changing "braketleft" to "bracketleft" has fixed the issue.

I had something wrong in my mind in that day, how could I possibly think that's the correct spell?

Sorry for the noise.
