### ISSUE TITLE
How to add to configuration.nix?

### ISSUE THREAD

**Issue by fearlessgeekmedia** [WillPower3309/swayfx#229]
### Please fill out the following:
- **Description:**
This is more of a question. It doesn't fit in either bugs or enhancements. How do I add swayfx to my configuration.nix in NixOS? Or can I not do that?

I tried setting programs.sway.package but that didn't work.

**Comment by AnotherRandomGitHubAccount** [comment]
I currently don't use nix, but have been trying to migrate there. issues like these make it very hard. Currently u can look at sway documentation on the nix documentation, maybe we could add documentation about swayfx there as well

**Comment by Aleksanaa** [comment]
Do you use a flake (There should be a flake.nix in /etc/nixos) or not?

**Comment by fearlessgeekmedia** [comment]
I didn't use a flake. I could, I suppose, but to add it to my sddm, wouldn't I need to set it up in my configuration.nix?

**Comment by WillPower3309** [comment]
https://github.com/WillPower3309/swayfx/issues/161
