### ISSUE TITLE
Blur not working with Firefox/Waterfox/Librewolf/...

### ISSUE THREAD

**Issue by usagi-flow** [WillPower3309/swayfx#231]
- **Swayfx Version:** `sway version 0.3.2`

- **Debug Log:** [Link to log](https://bin.disroot.org/?35fd78136a22001e#6wNPAwvcM3sXk1TsFh47fQZYpELZspL1yAS1PHosJdz4)

- **Configuration File:** [Link to file](https://bin.disroot.org/?ae3dda42835dc75f#2xuwnoeASe1k9pn9ctJzG6Pb4KoBQAF3RfKCKC1RPyJK) (I took the liberty to remove some commented lines, other than that, the configuration file is unchanged.)

- **Description:**

The blur effect does not apply to the transparent part of my browser. It works flawlessly for waybar and for my terminal (wezterm).

Interestingly, I _can_ get the blur to work in the browser, but only _after switching between light/dark mode_ using xdg-desktop-portal's `color-scheme`.
Even then, that will only work if the browser is _not_ floating, and the blur will disappear if I switch workspaces.

I could confirm the issue with all 3 browsers, which I all run in flatpak. I also ran my terminal in flatpak to rule out flatpak as a source of issues.

- **Steps to reproduce:**
  - Enable blur in the configuration.
  - Enable a transparent title bar in FF/WF/LW:
    - Enable native title bars if not done yet:
      - Rightclick somewhere next to the tabs -> Customize toolbar.
      - In the bottom left, enable "Title bar".
    - Open `about:config` and enable the option `toolkit.legacyUserProfileCustomizations.stylesheets` if it wasn't enabled yet.
    - Find out the profile directory by going into the Menu -> Help -> More troubleshooting information: The table contains an entry "Profile Directory".
    - In the profile directory, create a directory `chrome`, and in that directory, create a file `userChrome.css`
      - E.g. `~/.mozilla/firefox/xzxzyxzy.default-default/chrome/userChrome.css`
      - E.g. `~/.librewolf/xzxzyxzy.default-default/chrome/userChrome.css`
      - Or, if using Flatpak: E.g. `~/.var/app/io.gitlab.librewolf-community/.librewolf/xzxzyxzy.default-default/chrome/userChrome.css`
    - In `userChrome.css`, enter the following content:
      ```css
      #main-window {
          background-color: transparent !important;
      }
      #titlebar {
          background-color: transparent !important;
      }
      ```

Now, when (re)starting the browser, it should have a transparent tab bar background:
![image](https://github.com/WillPower3309/swayfx/assets/2804556/23c889c4-0ddf-44d1-9c6c-d3d7839f4f86)

If you ensure the window is not floating, and then switch between light/dark mode as follows:
`gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
`gsettings set org.gnome.desktop.interface color-scheme prefer-light`

...then the blur comes, until you switch workspaces or set the window floating:
![image](https://github.com/WillPower3309/swayfx/assets/2804556/529cf1dc-e27e-4b97-843c-772d8a6c0623)

**Comment by ErikReider** [comment]
Sounds most likely like Firefox isn't setting its opaque region when you're changing the background opacity.

We only render blur behind the window regions that the application reports are translucent. I'll investigate tomorrow but I'm pretty sure that there's nothing that can be done on our side

**Comment by ErikReider** [comment]
> (with respective performance consequences, I suppose).

The performance would be identical to a force blur option in these cases anyway. 

We currently don't have an option that forces blur. Wouldn't setting the opacity to something like 0.99 work?

**Comment by ErikReider** [comment]
Closing as it's a Firefox "bug"
