### ISSUE TITLE
Can't update system, wlroots dependency conflict

### ISSUE THREAD

**Issue by analyticmind** [WillPower3309/swayfx#236]
Sway version: 0.3.2-19414f6

Hello. I tried updating my system, Arch (kernel 6.1.61-1-lts), and get the following error:

"installing wlroots (0.17.0-1) breaks dependency 'libwlroots.so=11-64' required by swayfx
installing wlroots(0.17.0-1) breaks dependency 'wlroots<0.17' required by swayfx"

Any ideas on how to resolve this conflict?

Thanks!

**Comment by viktory683** [comment]
+1
but I think it's not a bug, but rather something like an update request.
0.17 wlroots, after all, break backward compatibility to some extent

**Comment by viktory683** [comment]
> Any ideas on how to resolve this conflict?

I think for now we can just ignore the new version of wlroots
with [yay](https://github.com/Jguer/yay) I can type something like `^3` to ignore
or edit `pacman.conf` adding wlroots to `IgnorePkg` section

```conf
...
IgnorePkg = wlroots
...
```

**Comment by analyticmind** [comment]
Thank you for the prompt reply! I have applied the update without the new wlroots version, and everything appears to be working normally.

**Comment by dron1885** [comment]
There is wlroots0.16 in Arch's extra repo. It doesn't conflict with normal wlroots (so no need to hold out on any updates) and enough for the Swayfx from the AUR.
