### ISSUE TITLE
not an issue per se, but it's time for a new release

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [WillPower3309/swayfx#241]
not a bug per se, but given this, I think it's time for a new release 

```
⮚ sudo pacman -Syyu
:: Synchronizing package databases...
 garuda                                                                                        97.4 KiB   180 KiB/s 00:01 [--------------------------------------------------------------------------] 100%
 core                                                                                         131.1 KiB  1092 KiB/s 00:00 [--------------------------------------------------------------------------] 100%
 extra                                                                                          8.3 MiB  7.95 MiB/s 00:01 [--------------------------------------------------------------------------] 100%
 multilib                                                                                     141.1 KiB  1455 KiB/s 00:00 [--------------------------------------------------------------------------] 100%
 chaotic-aur                                                                                    2.6 MiB  2.45 MiB/s 00:01 [--------------------------------------------------------------------------] 100%
 blackarch                                                                                      4.0 MiB  1395 KiB/s 00:03 [--------------------------------------------------------------------------] 100%
:: Starting full system upgrade...
warning: greetd-qtgreet: local (1.0.0-4.1) is newer than chaotic-aur (1.0.0-4)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing wlroots (0.17.0-1) breaks dependency 'libwlroots.so=11-64' required by swayfx
:: installing wlroots (0.17.0-1) breaks dependency 'wlroots<0.17' required by swayfx
```

**Comment by WillPower3309** [comment]
> not a bug per se, but given this, I think it's time for a new release 
> 
> ```
> ⮚ sudo pacman -Syyu
> :: Synchronizing package databases...
>  garuda                                                                                        97.4 KiB   180 KiB/s 00:01 [--------------------------------------------------------------------------] 100%
>  core                                                                                         131.1 KiB  1092 KiB/s 00:00 [--------------------------------------------------------------------------] 100%
>  extra                                                                                          8.3 MiB  7.95 MiB/s 00:01 [--------------------------------------------------------------------------] 100%
>  multilib                                                                                     141.1 KiB  1455 KiB/s 00:00 [--------------------------------------------------------------------------] 100%
>  chaotic-aur                                                                                    2.6 MiB  2.45 MiB/s 00:01 [--------------------------------------------------------------------------] 100%
>  blackarch                                                                                      4.0 MiB  1395 KiB/s 00:03 [--------------------------------------------------------------------------] 100%
> :: Starting full system upgrade...
> warning: greetd-qtgreet: local (1.0.0-4.1) is newer than chaotic-aur (1.0.0-4)
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing wlroots (0.17.0-1) breaks dependency 'libwlroots.so=11-64' required by swayfx
> :: installing wlroots (0.17.0-1) breaks dependency 'wlroots<0.17' required by swayfx
> ```

This should be the case for upstream sway too, we'll make a release once they drop a release based on wlroots 0.17

**Comment by 4rtemis-4rrow** [comment]
alright, thanks
