### ISSUE TITLE
Pacman error regarding wlroots and swayfx

### ISSUE THREAD

**Issue by Brittle73** [WillPower3309/swayfx#242]
Hello,

Starting within the last week or so I get the error below when trying to use pacman to update my Arch system. I have been able to get the rest of the stuff to update via yay and excluding wlroots, and usually if there is a small, wonky issue with updates like this it gets resolved quickly with further updates, but not yet here. I poked through the Issues page and did some Googling and am not seeing this issue, at least as far as my Goog-Fu goes. Is this a known issue? Do I likely have something misconfigured? Possibly I just need to uninstall the main pacman wlroots package? Is there another log, etc. that you need for troubleshooting that I may not have known about? I'd be surprised if nobody else was reporting this issue, but then again that's also assuming that I am _not_ the only one experiencing it, so I figured I'd pass it by you.

Thanks!

Error text:
:: Synchronizing package databases...
 core                             131.0 KiB   665 KiB/s 00:00 [#################################] 100%
 extra is up to date
 community                         45.0   B   849   B/s 00:00 [#################################] 100%
 multilib is up to date
 linux-surface is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing wlroots (0.17.0-1) breaks dependency 'libwlroots.so=11-64' required by swayfx
:: installing wlroots (0.17.0-1) breaks dependency 'wlroots<0.17' required by swayfx

Machine details:
- sway version 0.3.2-19414f6 (Jul 11 2023, branch 'master') (swayfx, obviously)
- Arch (up to date)
- MS Surface Pro 6
- i5
- 8GB RAM
- All other packages up to date via yay

Screenshot:
![image](https://github.com/WillPower3309/swayfx/assets/84404407/25810a3a-7473-497c-aeed-be7c19df06e3)

**Comment by zhurai** [comment]
You would probably want to install `wlroots0.16` from the extra arch repos (uninstall wlroots 0.17 for now)

I was having this issue myself until I found a post about this (but I don't remember where I saw this - took awhile of digging around though)

For what it's worth, you need to do this with regular sway currently as well: https://archlinux.org/packages/extra/x86_64/sway/   -->  libwlroots.so=11 (wlroots0.16)

**Comment by WillPower3309** [comment]
> You would probably want to install `wlroots0.16` from the extra arch repos (uninstall wlroots 0.17 for now)
> 
> I was having this issue myself until I found a post about this (but I don't remember where I saw this - took awhile of digging around though)
> 
> For what it's worth, you need to do this with regular sway currently as well: https://archlinux.org/packages/extra/x86_64/sway/   -->  libwlroots.so=11 (wlroots0.16) 

Thanks! Closing, this will be resolved once upstream sway supports wlroots 17, and we perform a rebase

**Comment by Brittle73** [comment]
Sorry for the delay guys, it's been a hell of a month.

I just wanted to confirm that although the issue with wlroots 17 and Sway appears to not have been resolved, I was able to forcefully uninstall 17 and then install 16 per @zhurai recommendation. It looks like pacman is happy now. Thanks!

**Comment by Brittle73** [comment]
Just kidding... I now cannot log into my SwayFX session after a reboot. I will hop back over to 17 for now.

**Comment by Brittle73** [comment]
Fixed it for now using the comment by Raineling on: https://www.reddit.com/r/swaywm/comments/18vja7b/updated_wlroots_yesterday_and_now_sway_doesnt_load/

yay -S --rebuild libliftoff wlroots wlroots0.16 swayfx swaybg swayidle swaylock

...and can now launch SwayFX.
