### ISSUE TITLE
installing wlroots (0.17.0-1) breaks dependency 'wlroots<0.17' required by swayfx

### ISSUE THREAD

**Issue by owpk** [WillPower3309/swayfx#244]
Is there plans to move to wlroots 17 ?

**Comment by b0o** [comment]
Same issue here. For now, I've added `IgnorePkg = wlroots` in the `[options]` section of my `/etc/pacman.conf` to skip the `wlroots` update.

**Comment by mr-casanova** [comment]
Hey, everyone! There's a helpful package in the official Arch repositories called **wlroots0.16**. This package can be installed independently of the upstream `wlroots` package, and it seems to have been designed to address issues like the one I encountered.

In my case, I wanted to install `labwc` from the official repo, but it conflicted with an older version of `wlroots` (version **0.16**, as required by labwc). Fortunately, I stumbled upon the `wlroots0.16` package.

Here's the command sequence I used:
`sudo pacman -Rdd wlroots  # Remove wlroots forcefully`
`sudo pacman -S wlroots0.16 wlroots`

Now you have `wlroots0.16` installed for packages that require `libwlroots.so=11`, alongside the upstream `wlroots`.

I believe it might be beneficial to reconsider the "Build" section in most repository Readme files. It would be helpful to include information about building projects with different types of library linking (statically or dynamically).

**Comment by viktory683** [comment]
There is a package called `downgrade` (`aur/downgrade`)
If U somehow installed wlroots 17 U can easily downgrade and automatically add it to `IgnorePkg`
```bash
sudo downgrade wlroots
```
![image](https://github.com/WillPower3309/swayfx/assets/35001580/2a804336-3102-4cff-810a-9a2730afa796)

**Comment by X1mper** [comment]
I'm really looking forward to the update. Just yesterday I updated wlroots in alt sisyphus :)

**Comment by WillPower3309** [comment]
We're hoping to get a release out asap, but there are some prerequisite steps we need to take first

**Comment by WillPower3309** [comment]
rebase complete, will be fixed by release (or is fixed already on git version)
