### ISSUE TITLE
Blur improvements

### ISSUE THREAD

**Issue by ozwaldorf** [WillPower3309/swayfx#249]
The current blur implementation could be enhanced with a configurable noise pass to reduce banding on high blur setting, as well as settings for contrast/brightness. These features were recently added to hyprland, and drastically improved the blur appearance and usability.

The noise pass can effectively remove banding, especially when wallpapers do not have a wide range of colors. For example, many wallpapers produced with [lutgen](https://github.com/ozwaldorf/lutgen-rs) will start banding when blurred, due to a much lower contrast between pixels.

The brightness and contrast settings are also a good QOL addition, as you can setup a look similar to MacOS, which lowers these values so that the blur does not conflict with the window's contents. These tweaks help maintain readability in applications such as the terminal.

**Comment by ErikReider** [comment]
> For example, many wallpapers produced with [lutgen](https://github.com/ozwaldorf/lutgen-rs) will start banding when blurred, due to a much lower contrast between pixels.

Could you provide a screenshot?

> The brightness and contrast settings are also a good QOL addition, as you can setup a look similar to MacOS, which lowers these values so that the blur does not conflict with the window's contents.

Could you also provide screenshots for this? Would be nice to see a comparison :)

**Comment by ozwaldorf** [comment]
Sure, here's some examples, I'll add what swayfx looks like with similar settings in a sec

## Hyprland Examples

No noise, full contrast and brightness:
![image](https://github.com/WillPower3309/swayfx/assets/8976745/f6075a66-43d8-4d21-81f0-421103f9bea8)

Noise 0.02, full contrast and brightness:
![image](https://github.com/WillPower3309/swayfx/assets/8976745/4a0e64ee-955b-4f24-8621-66e0817eb664)

Noise 0.02, default contrast and brightness:
![image](https://github.com/WillPower3309/swayfx/assets/8976745/be55b725-b887-4759-9f63-46ed451d24f3)

**Comment by ozwaldorf** [comment]
I was able to hack in hyprland's noise shader:

```glsl
precision         mediump float;
varying vec2      v_texcoord;
uniform sampler2D tex;

uniform float     noise;

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

void main() {
    vec4 pixColor = texture2D(tex, v_texcoord);

    float noiseHash   = hash(v_texcoord);
    float noiseAmount = (mod(noiseHash, 1.0) - 0.5);
    pixColor.rgb += noiseAmount * noise;

    gl_FragColor = pixColor;
}
```

which looks nice and on par with hyprland (noise 0.02):
![image](https://github.com/WillPower3309/swayfx/assets/8976745/b3de63dc-97f8-4e30-8eba-aabdc03ad747)

**Comment by WillPower3309** [comment]
> I was able to hack in hyprland's noise shader in an experiment https://github.com/ozwaldorf/swayfx/commit/253435a5675229b91735d81a90dd039f66567488
> 
> which looks nice and on par with hyprland (noise 0.02):
> ![image](https://github.com/WillPower3309/swayfx/assets/8976745/b3de63dc-97f8-4e30-8eba-aabdc03ad747)

Feel free to open a PR! Great stuff :D
