### ISSUE TITLE
[minor] more descriptive version

### ISSUE THREAD

**Issue by mazunki** [WillPower3309/swayfx#253]
The version number is misleading.
```sh
~ sway --version
sway version 0.3
```

I feel this should at the very least say `swayfx version 0.3`, cuz I thought I was behind several version of sway itself. Ideally, maybe something like the following:

```sh
~ sway --version
swayfx version 0.3.2 (based on sway 1.8.1)
```

**Comment by WillPower3309** [comment]
completed in #254
