### ISSUE TITLE
build failure in voidlinux

### ISSUE THREAD

**Issue by moilong** [WillPower3309/swayfx#27]
Tried to build swayfx/master and getting this error:
[void@mnbvcxz swayfx]$ ninja -C build/
ninja: Entering directory `build/'
[78/285] Compiling C object sway/sway.p/desktop_render.c.o
FAILED: sway/sway.p/desktop_render.c.o 

../sway/desktop/render.c: In function 'output_render':
../sway/desktop/render.c:1269:2: error: a label can only be part of a statement and a declaration is not a statement
 1269 |  struct wlr_renderer *wlr_renderer = output->server->wlr_renderer;
      |  ^~~~~~
[80/285] Compiling C object sway/sway.p/desktop_output.c.o
ninja: build stopped: subcommand failed.

**Comment by moilong** [comment]
Installed version is wlroots-0.15.1 and wayland-protocols 1.26 but I cloned them as subprojets from gitlab for swayfx. Im attaching meson log.
[meson-log.txt](https://github.com/WillPower3309/swayfx/files/9883712/meson-log.txt)

**Comment by ErikReider** [comment]
Seems like `wayland-protocols` isn't installed: `Dependency 'wayland-protocols' is required but not found.` on line 871 in the log

**Comment by moilong** [comment]
As I mentioned above wayland-protocols already installed. I can successfully build and run [https://github.com/swaywm/sway](url) and [https://github.com/fluix-dev/sway-borders](url) on this machine.

**Comment by ErikReider** [comment]
This is based off of Sway 1.7. Try building that and see if there's an issue :)

**Comment by moilong** [comment]
sway 1.7 shows the same error during meson build but ninja -C build finished successfully and sway-1.7 running without issues.

**Comment by WillPower3309** [comment]
Should be fixed now, please retry with the lastest master :)

**Comment by moilong** [comment]
Yes.Thankyou. Love that real corner radius!
