### ISSUE TITLE
SwayFX Fails to Run on Fedora 39

### ISSUE THREAD

**Issue by cprin21** [WillPower3309/swayfx#271]
- **Swayfx Version:**
-sway version 0.3.2

- **Error Output**
```
sway: render/gles2/renderer.c:43: gles2_get_renderer: Assertion 'wlr_renderer_is_gles2(wlr_renderer)' failed.
[main.c:582] wl_display_roundtrip failed
```

- **Description:**
- Install SwayFX via Fedora COPR
- Run SwayFX via sway command
- Does not run

**Comment by ErikReider** [comment]
Hmmm. Works perfectly fine on my Fedora 39 install... Have you tried running it nested?

**Comment by RicArch97** [comment]
Also works for me

![20240203_203445](https://github.com/WillPower3309/swayfx/assets/61013287/985c6240-3b31-45db-86bb-ecd36fa7e584)

**Comment by ErikReider** [comment]
What OpenGL drivers are you running?

**Comment by cprin21** [comment]
Can confirm it's working now, and I cannot explain why I was having issues getting it to install.
