### ISSUE TITLE
vscodium new window not being rendered

### ISSUE THREAD

**Issue by Iss-in** [WillPower3309/swayfx#276]
For the last year or so, vscode was crashing on sway/wayland if run in wayland mode,  The latest version 1.86 solves that, but it also introduced a new bug, which is making a 2nd window of vscode unable to render.

https://github.com/microsoft/vscode/issues/204597

This was fixed by sway commit https://github.com/swaywm/sway/commit/07b059852673cd9e148c2adfc6bb4f8a0d0ff315 and wlroots commit https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/54e1fefd2e29cb00dff7c02801913d793ceab7d6

can we please add the sway fix here

**Comment by notpeelz** [comment]
I applied the sway patch you linked against the current release of swayfx but the issue still occurs.
The wlroots commit you linked doesn't do anything either.

hashworks (from the vscode issue) is saying he couldn't reproduce the issue when testing with the latest sway/wlroots changes, and not that these specific commits fixed the issue.

**Comment by Iss-in** [comment]
weird, i will look more into this to single out the commit, latest sway/wlroots indeed fixed the issue. i thought hashworks info was credible

**Comment by Iss-in** [comment]
sorry for the bad info earlier, seems like latest sway release ( 1.9.1 ) has fixed the issue

**Comment by WillPower3309** [comment]
Hey @Iss-in , not sure if you're using swayfx-git, but the rebase is complete. Please let me know if you do and if it fixes the issue :)

**Comment by Iss-in** [comment]
thanks, will take a look, it seems that scenefx doesnt have an aur package yet, and neither as a dependency in swayfx-git aur package. installing it manually

**Comment by ErikReider** [comment]
> thanks, will take a look, it seems that scenefx doesnt have an aur package yet, and neither as a dependency in swayfx-git aur package. what version of wlroots is needed to build scenefx ?

It's currently not building, waiting for https://github.com/WillPower3309/swayfx/pull/290. https://github.com/wlrfx/aur-packages/pull/1 is needed for the AUR packages to be uploaded / updated.

You can build it right now though if you build swayfx with scenefx and wlroots 0.17 as subprojects :)

**Comment by Iss-in** [comment]
thanks, i tried, and sway seems to be crashing when i move mouse or launch some app ( firefox ) 
[Uploading sway.log…]()

**Comment by ErikReider** [comment]
The new aur packages are now up and running! :)

**Comment by Iss-in** [comment]
thanks, seems to be working fine, getting some weird behaviour with borders tho

https://github.com/WillPower3309/swayfx/assets/36916613/fdfa5ba1-c66b-452c-b99e-39679a29185e


    # Swayfx settings 
    corner_radius 6
    shadows enable
    shadow_color #000000ff
    shadow_blur_radius 6
    shadows_on_csd on
    # exec_always sway_theme -r
    smart_corner_radius disable

    blur enable
    blur_radius 6
    blur_passes 6
    blur_xray enable
    scratchpad_minimize disable

**Comment by WillPower3309** [comment]
> thanks, seems to be working fine, getting some weird behaviour with borders tho
> 
> https://github.com/WillPower3309/swayfx/assets/36916613/fdfa5ba1-c66b-452c-b99e-39679a29185e
> 
> 
>     # Swayfx settings 
>     corner_radius 6
>     shadows enable
>     shadow_color #000000ff
>     shadow_blur_radius 6
>     shadows_on_csd on
>     # exec_always sway_theme -r
>     smart_corner_radius disable
> 
>     blur enable
>     blur_radius 6
>     blur_passes 6
>     blur_xray enable
>     scratchpad_minimize disable
> 

Hmm this is alarming! Mind opening a new issue for this? :) I can take a look at it shortly

**Comment by Iss-in** [comment]
weirdly its also reproducible in upstream release version, happens only when i resize by mouse, but not with keyboard shortcuts

**Comment by WillPower3309** [comment]
> weirdly its also reproducible in upstream release version, happens only when i resize by mouse, but not with keyboard shortcuts
> 
> will file issue there

Thanks! Feel free to link to it here if you do

**Comment by WillPower3309** [comment]
Link to upstream issue: https://github.com/swaywm/sway/issues/8125
