### ISSUE TITLE
Add Git only to shadow_offset on readme

### ISSUE THREAD

**Issue by adityavishwakarma69** [WillPower3309/swayfx#278]
I found the option shadow_offset in the Readme of the github page.
It was not working so after a bit of searching i found out that it was merged on december of 2023 (after the latest release 0.3.2)
I am not asking you to rush new release but can you just edit the readme so other people don't face the same.

Thank you

**Comment by WillPower3309** [comment]
fixed by https://github.com/WillPower3309/swayfx/commit/62472238caa0cba06e8186e3adfb36ade65e6ce3
