### ISSUE TITLE
Add Fedora copr

### ISSUE THREAD

**Issue by hifinerd** [WillPower3309/swayfx#28]
### Please fill out the following:
- **Description:**
I would like for there to be an officially sanctioned copr repo for swayfx, to allow for easier installation and updates on Fedora systems.

**Comment by ErikReider** [comment]
Mentioned in https://github.com/WillPower3309/swayfx/issues/12#issuecomment-1286676265 but good to have as a separate issue

**Comment by ErikReider** [comment]
The only "issue" that I've experienced with writing spec files is the tedious process of manually writing each build files output location. SwayNC example:

```spec
%files
%doc README.md
%{_bindir}/swaync-client
%{_bindir}/swaync
%license COPYING
%{_sysconfdir}/xdg/swaync/configSchema.json
%{_sysconfdir}/xdg/swaync/config.json
%{_sysconfdir}/xdg/swaync/style.css
etc...
```

**Comment by ErikReider** [comment]
Also, which account should this be published on. I've got a account on the Copr website but do you @WillPower3309 prefer a more official one? Same goes for the AUR #12 issue

**Comment by WillPower3309** [comment]
> Also, which account should this be published on. I've got a account on the Copr website but do you @WillPower3309 prefer a more official one?

Good question, perhaps we should have an official SwayFX account!

**Comment by WillPower3309** [comment]
@ErikReider seeing as we're very close to the 0.1 release, I wanted to ask a question in relation to this issue. I know we don't have the version auto increment yet, is there anything ill need to do manually to get this to work once 0.1 is released, or will it all be automated?

**Comment by ErikReider** [comment]
> I know we don't have the version auto increment yet, is there anything ill need to do manually to get this to work once 0.1 is released, or will it all be automated?

The only thing that you'll need to do before releasing and tagging is bumping the version numbers of the spec file and the eventual PKGBUILD.

The fedora-build GitHub action will make sure that it builds correctly with the spec file. I'll have to add one for Arch this weekend when I finally have enough time to finish the PKGBUILD :)
