### ISSUE TITLE
Lack of title and unexpected transparencies in waterfall mode

### ISSUE THREAD

**Issue by gorylong** [WillPower3309/swayfx#293]
### Please fill out the following:
- **Swayfx Version:**
sway version 0.3.2-26cdeeb (Mar 11 2024, branch 'master')

- **Debug Log:**
<script src="https://gist.github.com/gorylong/03c86baf7e0388b3b29465f9c5229a97.js"></script>

- **Configuration File:**
<script src="https://gist.github.com/gorylong/d7e65657b8328011da17c70ee07f3d06.js"></script>

- **Description:**
transparent spaces appear and in some windows the title disappears when I stack the windows in cascade
![2024-04-14_23:10:34](https://github.com/WillPower3309/swayfx/assets/91983758/f7558d07-2373-4466-83f6-10e6b2d4fd11)

**Comment by WillPower3309** [comment]
Dup of #174 , has been fixed and will be released within the next week or so (although your package maintainers may need more time depending on which distro you're on)
