### ISSUE TITLE
Minor improvement: Round tiling_drag rect

### ISSUE THREAD

**Issue by ErikReider** [WillPower3309/swayfx#30]
### Please fill out the following:
- **Description:**
Math the window below by rounding the tiling_drag (floating_mod + left mouse) rect.

![swappy-20221111_212633](https://user-images.githubusercontent.com/35975961/201426260-4e576634-77cc-4ffc-be37-b755dbb43a12.png)

**Comment by WillPower3309** [comment]
Good call
