### ISSUE TITLE
Saturation not working

### ISSUE THREAD

**Issue by FedericoCapoccia** [WillPower3309/swayfx#304]
- **Swayfx Version:**
swayfx version 0.4-0c80434 (Apr 29 2024, branch 'master') (based on sway 1.9.0)

- **Debug Log:**
https://gist.github.com/FedericoCapoccia/99a1966ca0e7f629031933ea9a25a5e7

- **Configuration File:**
https://gist.github.com/FedericoCapoccia/94e52db9d0870d9f764f2c71d0479e58

- **Description:**
Modify the config file
Either reboot or reload with 'swaymsg reload' or by hotkey

**Comment by tylerdq** [comment]
Why is this not planned to be fixed? It's one of the features discussed in the configuration options section of the readme.

Saturation was working for me before upgrading to v0.4 and now it's broken. Is this something that can be revisited?

**Comment by ErikReider** [comment]
@WillPower3309 how do you want to move forward with this? The saturation feature adds latency to fullscreen applications, so it's not really that good for gaming… The later color stuff in wlroots would replace this in the future. Remove the feature?

**Comment by tylerdq** [comment]
I would like to advocate for this feature. It's an optional setting that users like me can use (and set a shortcut to toggle) as per their needs. I'm also willing to explore contributing to support the feature. Though I would need to do a lot of learning to contribute to the codebase, that's something I'd like to explore to keep this supported in the package.

**Comment by tylerdq** [comment]
> The later color stuff in wlroots would replace this in the future. Remove the feature?

I'm not familiar with the planned features for wlroots. Could you help me find where to learn more about this? If it will be built into wlroots in the future maybe that would be a better place for me to focus my contribution efforts.
