### ISSUE TITLE
Add support for blur to swaybar.

### ISSUE THREAD

**Issue by MubinMuhammad** [WillPower3309/swayfx#309]
As swaybar is part of the sway ecosystem, as the blur effect doesn't work with swaybar, it's a part that should be fixed soon.

**Comment by thnikk** [comment]
This is already possible with `layer_effects "panel" blur enable`.

**Comment by MubinMuhammad** [comment]
Does that work in your system? Because it has no effect on my swaybar. Which I did set to transparent with:
```
bar {
  swaybar_command swaybar
  status_command /usr/bin/i3status-rs $HOME/.config/sway/i3status_config.toml
  position top
  gaps 8
  height 36
  font pango:CaskaydiaCove Nerd Font Bold 12
  colors {
    background #1d202160            # <----- here
    focused_workspace #ddb36e #d8a657 #1d2021
  }
}
```

and it doesn't seem to work

**Comment by scorpius2k1** [comment]
background #RRGGBBAA - the higher the alpha 'AA' value is, RGB values will be more visible, but blur will become less visible. A good value to try for the alpha channel if used with color could be 66. So a "red" bar with blur could be background #FF000066. Try a few different wallpapers as well, brighter/dark/light contrasting, etc. help the blur effect to stand out more.

This works on my end with swayfx version 0.4.

Configure and reload your swayfx config:

```
layer_effects "panel" blur enable

bar {
    position top

    colors {
        # Text color of status bar
        statusline #ffffff
        # Background of status bar
        background #00000000
    }
}
```
`background #00000000`
![2024-05-02_08-53-01](https://github.com/WillPower3309/swayfx/assets/25441483/6c8f0a58-b864-4bd3-aa72-0590e7ea839d)
`background #FF000066`
![2024-05-02_09-00-13](https://github.com/WillPower3309/swayfx/assets/25441483/5094f200-46ed-47ca-927d-abb3e02776b6)
`background #1d202166`
![2024-05-02_09-06-37](https://github.com/WillPower3309/swayfx/assets/25441483/005f87ca-2fca-451e-a77f-dad217650297)

**Comment by MubinMuhammad** [comment]
Thanks, I have updated swayfx, and blur is working as it should!
