### ISSUE TITLE
borders not on edges of clients

### ISSUE THREAD

**Issue by exoess** [WillPower3309/swayfx#310]
- **Swayfx Version:**
  - `swayfx version 0.4-e45b420c (May  2 2024, branch 'master') (based on sway 1.9.0)`

- **Debug Log:**
  - https://pastebin.com/Kfs7ELjV

- **Configuration File:**
   -  https://pastebin.com/RSWkbTTe

- **Description:**
  - Resize a floating instance of foot until gaps between the border and window appear

**Comment by DreamMaoMao** [comment]
https://github.com/WillPower3309/swayfx/assets/30348075/fb2d9b29-f800-4096-b894-b7fa238aae7f

sway 1.19 also has this issue, not only swayfx

**Comment by exoess** [comment]
should i make the issue on sway too?

**Comment by ErikReider** [comment]
> should i make the issue on sway too?

Create the issue there and I'll close it here :)

**Comment by WillPower3309** [comment]
Feel free to link the issue here for tracking!
