### ISSUE TITLE
[Fedora 40] Can't install from the copr repository

### ISSUE THREAD

**Issue by Gwenodai** [WillPower3309/swayfx#311]
It's not possible to install from the fedora copr at the moment due to missing packages. Trying to install gives this error as the only packages on the copr are swayfx and scenefx.

```
Error: 
 Problem: conflicting requests
  - nothing provides swayfx-config needed by swayfx-0.4-1.fc40.x86_64 from copr:copr.fedorainfracloud.org:swayfx:swayfx

```

**Comment by theshatterstone** [comment]
@ErikReider Can you confirm why this was closed, as I'm currently having the exact same issue, also on Fedora 40? Thanks.

**Comment by Gwenodai** [comment]
@theshatterstone I assume the copr must only exist for scenefx considering this got closed instantly with no response. You're just gonna have to compile it yourself.

**Comment by theshatterstone** [comment]
@Gwenodai  Thanks, but I'm very much anti-compliation as I think all users repeatedly compiling their software is a waste of time, and I just don't like compiling from source in general (bye bye updates from the package manager) so I think I'll just stick to Hyprland and use Sway when I want to try out manual tiling in the near future.
