### ISSUE TITLE
Take a look at the .builds files

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#34]
### Please fill out the following:
- **Description:**
It looks like the sway project makes use of the `.builds` directory to store some build information. We should use these in our deployment actions!

Let's aim to take a look at these for the 0.2 release.

CC @ErikReider

**Comment by ErikReider** [comment]
What do you prefer, GitHub Actions or the SourceHut system that Sway uses? The existing SH build scripts could probably be used in GH Actions

**Comment by WillPower3309** [comment]
Ah gotcha, wasn't sure if they were sourcehut specific or not, I think I'll clear them out of this project then
