### ISSUE TITLE
Special Workspaces

### ISSUE THREAD

**Issue by Stoppedpuma** [WillPower3309/swayfx#340]
### Please fill out the following:
- **Description:**
Special Workspaces are a feature on Hyprland which work similarly to scratchpad by being an overlay, a Special Workspace is different as it's an entire workspace instead of just one window.

Example video:

https://github.com/user-attachments/assets/07932bd4-fe8b-4791-9eba-0a695b8d7396

**Comment by ozwaldorf** [comment]
You might be able to accomplish something even similar by making a container, moving other windows into it, either tabbed or split, and moving that into the scratchpad

**Comment by Stoppedpuma** [comment]
I'll look into that approach for now, I think this might become an issue when trying to manage multiple containers though? e.g manually opening the scratchpad for container 1, 2, 3 etc? I'll see what I can manage.

**Comment by markstos** [comment]
I can confirm that the Sway scratchpad can be a container that contains multiple windows.

I'm opposed to adding "special workspaces" to Swayfx. If the scope of Swayfx continues to increase beyond adding a bit of eyecandy, it will get more and more difficult to maintain and keep it sync'ed with Sway.

**Comment by ErikReider** [comment]
> I can confirm that the Sway scratchpad can be a container that contains multiple windows.
> 
> 
> 
> I'm opposed to adding "special workspaces" to Swayfx. If the scope of Swayfx continues to increase beyond adding a bit of eyecandy, it will get more and more difficult to maintain and keep it sync'ed with Sway. 

Yeah, I agree. It's already a bit difficult to maintain with the current non-effects features xD

**Comment by Stoppedpuma** [comment]
Will close this as I have been using the container solution for a few months now. It's definitely has it's slight annoyances and limitations but It's not experience ruining.
