### ISSUE TITLE
HiDPI fork support on Arch

### ISSUE THREAD

**Issue by tyush** [WillPower3309/swayfx#37]
- **Description:**
Currently, the PKGBUILD for swayfx depends both on `libwlroots.so` and `wlroots<0.16`. 

Is there a specific reason for it to depend on both the library and specifically `wlroots`? This is preventing me from using `wlroots-hidpi-git` with swayfx.

**Comment by ErikReider** [comment]
Swayfx is based off of sway 1.7 so it depends on wlroots 0.15

**Comment by WillPower3309** [comment]
Is sway itself able to work with that fork? I haven't tried using alternative forks myself yet, but if sway does, then swayfx would be able to as well, and I could look into it.

**Comment by tyush** [comment]
> Is sway itself able to work with that fork? I haven't tried using alternative forks myself yet, but if sway does, then swayfx would be able to as well, and I could look into it.

Ah, that checks out. I was under the impression that I was using vanilla sway; turns out it was a fork made to work with the HiDPI wlroots fork, which would explain why swayfx is unable to build using that.

**Comment by WillPower3309** [comment]
Ah, sorry to hear. Hopefully HiDPI support gets merged upstream!
