### ISSUE TITLE
Animations suggestion

### ISSUE THREAD

**Issue by moilong** [WillPower3309/swayfx#43]
Since you mentioned "swayfx 1.0 will include all of the popular picom compositor effects" I like you to have a look at this picom fork https://github.com/FT-Labs/picom
Animations,blur,corner radius and other effects are excellent in this fork. Im using it in berry wm. This is the dev's unixporn post https://teddit.net/r/unixporn/comments/x9yp34/dwm_hi_everyone_lots_of_new_unique_animations_for/

**Comment by Selmer443** [comment]
I think those animations look great as well, but for something on wayland wouldn't hyprlands animations be more in line with this current project? hyprland animations are also smoother IMO, not sure if this is just a screen tearing issue for me or something similar, but on 240hz monitors hyprland animations are as good as it gets.

**Comment by WillPower3309** [comment]
Once I get to the point of adding animations I'll take a look at hyprlands implementation as well as the picom one to see which one seems better. Ideally we'd have an even better implementation than the (friendly) competition, so I'll be consulting some other literature as well :)

**Comment by WillPower3309** [comment]
I think this is emcompassed in #7 and #8, so closing. Further discussion on fade animations / movement animations are encouraged there! :)

**Comment by WillPower3309** [comment]
I think this is emcompassed in #7 and #8 so closing. Further discussion is encouraged there!
