### ISSUE TITLE
Documentation of new config variables in readme

### ISSUE THREAD

**Issue by zoro11031** [WillPower3309/swayfx#44]
EDIT: I just realized that there is a "New Configuration Options" sections, but it's unclear if it's a comprehensive list of new options compared to sway, or new to the latest swayfx update. I assumed the latter but I now realize it's the former.

**Add a brief summary and description of new variables that swayfx has to the README **

Currently the new variables are found in the example config document. This isn't immediately obvious and might take some people a few minutes to find. There should be a brief list of new variables to use in swayfx that don't exist in sway, or a line in the readme guiding users to consult the included example config file. It doesn't seem like there are a lot of new variables just yet so it would probably save some time and headache to add the documentation now and update it as the project grows :)

Thank you for your work on this!

**Comment by WillPower3309** [comment]
Thanks for the issue, it's good feedback to hear this, I'll try to make the config changes more clear and centered in the readme!

**Comment by WillPower3309** [comment]
Adding to 0.2 milestone as the readme will be need to be made more clear with further config options
