### ISSUE TITLE
Part of window disappears on vertical monitor

### ISSUE THREAD

**Issue by GlitchyCrafting** [WillPower3309/swayfx#47]
Swayfx Version: 0.1-1 from AUR

Using Default Config file but with monitors arranged how I need them.

The bottom corner of any application gets removed, more of that corner disappears when multiple windows are opened and it only affects the bottom-most window. Also affects context menus in Firefox and Chrome. None of these happen on my other two monitors, only my vertical one.

### Alacritty
![2022-11-15T18:43:56,017473247-06:00](https://user-images.githubusercontent.com/74939524/202056374-a3ec62bf-af5d-4ce1-91f9-fbffcf26e4d7.png)
### Firefox
![2022-11-15T18:44:20,288487318-06:00](https://user-images.githubusercontent.com/74939524/202056377-3b787347-90fa-433c-9791-7fde28ae51b8.png)
### Multiple Windows
![2022-11-15T18:44:31,823462145-06:00](https://user-images.githubusercontent.com/74939524/202056379-4e835086-cf79-43d4-af0e-a3cf847d86ad.png)
### Chromium
![2022-11-15T18:55:07,826845375-06:00](https://user-images.githubusercontent.com/74939524/202056894-d0b8eb61-f61d-45b4-9a1a-6f05a034d9ef.png)
# PCManFM-GTK3
![2022-11-15T18:57:01,282353951-06:00](https://user-images.githubusercontent.com/74939524/202057082-1f4bebb5-2574-477a-ad48-19ff85d0fdb0.png)

**Comment by ErikReider** [comment]
The even weirder thing about this is that I can't replicate this issue when running swayfx in nested mode (open another swayfx instance inside of swayfx), just when starting it from a tty???

**Comment by ErikReider** [comment]
I've narrowed it down to the `tex_*.frag` shaders. Seems like the `quad_round_*.frag` shaders ara also experiencing this bug

**Comment by ErikReider** [comment]
https://github.com/WillPower3309/swayfx/blob/7ccabdad2f0699735a79a001dc1af5a4a46dc5cd/sway/desktop/shaders/tex_rgbx.frag#L23-L30

https://github.com/WillPower3309/swayfx/blob/7ccabdad2f0699735a79a001dc1af5a4a46dc5cd/sway/desktop/shaders/tex_rgba.frag#L24-L31

https://github.com/WillPower3309/swayfx/blob/7ccabdad2f0699735a79a001dc1af5a4a46dc5cd/sway/desktop/shaders/tex_external.frag#L26-L33

Seems to be the cause. Do you @WillPower3309 have any idea why this could happen?

**Comment by ErikReider** [comment]
Also seems like the rounded corners aren't visible on the vertical monitor either

**Comment by WillPower3309** [comment]
Yup, I think I know exactly what's wrong here! I'll take a look at a fix as soon as I can

**Comment by WillPower3309** [comment]
> I'm experiencing the same issue. Very weird... Could you check if base sway 1.7 experiences this @GlitchyCrafting 

Would you mind checking if rounded titlebars are strange too?

**Comment by ErikReider** [comment]
> Would you mind checking if rounded titlebars are strange too @ErikReider ? No worries if not, I can set up a vertical monitor

I also experienced issues with the filling and the corners of the titlebar. Weird bug :/

**Comment by frap129** [comment]
> Yup, I think I know exactly what's wrong here! I'll take a look at a fix as soon as I can

Came here to report the same bug, but it sounds like you've got it handled!

**Comment by frap129** [comment]
Still having this issue on the latest release :(

**Comment by WillPower3309** [comment]
Yup, sorry to say that it has not been fixed yet. Hoping to take a look soon

**Comment by ErikReider** [comment]
![image](https://user-images.githubusercontent.com/35975961/212773019-59000779-ebd2-4d77-9805-59c3506ac21b.png)
Maybe the sizing isn't correct?

Also flipping the width/height and x/y seems to do something. It's at least a step in the right direction
https://github.com/WillPower3309/swayfx/blob/1baba77c74302b8c1f212e851f194deae0fae46b/sway/desktop/fx_renderer.c#L426-L427
