### ISSUE TITLE
Rounded corners behave like gaps when smart_gaps on, i.e. no rounded corners when only one tiled window

### ISSUE THREAD

**Issue by jhpaques** [WillPower3309/swayfx#53]
- **Description:**
When `smart_gaps` is set to `on`, but rounded corners are added to all windows with and without gaps. When there are no gaps, it creates a small triangle of background (see screenshot bellow), which is quite ugly.
It would be better if the rounded corners behave like gaps when `smart_corners` is set to `on`, i.e. no rounded corners when there is only one window.
Alternatively, a new command like `smart_corners` could be used for this.

![Screenshot_2022-11-16T12:27:55+01:00](https://user-images.githubusercontent.com/61907053/202168697-c1879285-8971-4093-9e77-0ddb1baa22b7.png)

**Comment by WillPower3309** [comment]
Had to revert this due to a crash it was causing (likely in the `view_ancestor_is_only_visible(view)` function). Commit that reverts the change: https://github.com/WillPower3309/swayfx/commit/768be91e09ac59675041449571f0ad69d2f642c7

**Comment by WillPower3309** [comment]
Will look into bringing this back in a way that doesn't cause #72 again. Not sure what was wrong with the `view_ancestor_is_only_visible(view)` call

**Comment by WillPower3309** [comment]
In addition to functioning this way when smarts gaps are on, we should function like this when gaps are off and only one window is open as well.

**Comment by WillPower3309** [comment]
Hmm, an easy fix for this plus the case mentioned above would just be checking if the workspace has gaps when rendering surfaces, gonna try that tomorrow

**Comment by WillPower3309** [comment]
Fixed in https://github.com/WillPower3309/swayfx/commit/a6f60eeb31c341819611da9f844d4687b3160706
