### ISSUE TITLE
Why not use pcre2?

### ISSUE THREAD

**Issue by Mederim** [WillPower3309/swayfx#57]
Sway original fork is using pcre2 so why not swayfx is using?

**Comment by WillPower3309** [comment]
Swayfx is build off of sway 1.7, which uses pcre. Are you having any compilation errors or are you just curious about the pcre dependency?

Once the next version of sway is released we will rebase and likely need to use pcre2

**Comment by WillPower3309** [comment]
Going to assume that this is a question and not a big, so closing

**Comment by Mederim** [comment]
Hi again i questioned because i use pcre2 to build sway in my linux distribution so i tried to compile with this but i get errors

**Comment by WillPower3309** [comment]
> Hi again i questioned because i use pcre2 to build sway in my linux distribution so i tried to compile with this but i get errors

The current sway master branch uses pcre2. There has yet to be an official stable release with this update, so until then, SwayFX will use pcre. You'll have to install pcre to use swayfx, but we will update to pcre2 once sway has a stable release with it
