### ISSUE TITLE
Add drop shadows

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#6]
- **Description:**
swayfx should have drop shadows

**References**
 - [rendering rounded shadows optimally](https://madebyevan.com/shaders/fast-rounded-rectangle-shadows/)
- previous PR attempt in main repo: https://github.com/swaywm/sway/pull/4254
  - lot of things that I'd change here / that would be easier with the existing fx_renderer but worth the look

**Comment by WillPower3309** [comment]
Take a look at https://madebyevan.com/shaders/fast-rounded-rectangle-shadows/

**Comment by WillPower3309** [comment]
0.2 will focus on blur effects, will need to think of the priority of this vs #7

**Comment by Barbaross93** [comment]
Will it be possible to specify which windows have shadows? For example, including shadows on notification popups, panels, or floating windows only?

**Comment by WillPower3309** [comment]
> Will it be possible to specify which windows have shadows? For example, including shadows on notification popups, panels, or floating windows only?

Absolutely!
