### ISSUE TITLE
Dim inactive windows?

### ISSUE THREAD

**Issue by winteriscariot** [WillPower3309/swayfx#63]
Was wondering if it'd be possible/planned to add a function to either dim or blur inactive (aka, unfocused) windows, similar to what picom can do. I was thinking this might be a nice enhancement for floating windows, effectively mimicking a "monocle" view: one floating window front and center while all the other windows are dimmed/blurred

**Comment by WillPower3309** [comment]
Could be useful to have the dim apply as a fade lighter / darker effect once #7 is complete
