### ISSUE TITLE
Ignore dim on certain windows

### ISSUE THREAD

**Issue by famfo** [WillPower3309/swayfx#68]
With `dim_inactive`, some windows get dimmed that I would like to not be dimmed, like my browser for example. I would propose that you can use `for_window` to set the dim for certain windows. For example:

`for_window [app_id="LibreWolf"] dim_inactive 0`

Experimenting with this, I found a bug. When I set the `for_window` like this, and I open a new tab, `dim_inactive` gets ignored globally until I reload sway. So I am not sure if this is a bug or not implemented yet.

**Comment by ErikReider** [comment]
We haven't added `for_window` support yet. I'll look into it :)

**Comment by head-gardener** [comment]
Could you please clarify, your issue is that after reloading the config your opened windows ignore it?
