### ISSUE TITLE
Execute command on focus/unfocus

### ISSUE THREAD

**Issue by Vulldozer** [WillPower3309/swayfx#74]
### Please fill out the following:
- **Description:**
I would love to be able to execute a shell command/script whenever I focus/unfocus a certain window.

This can be implemented into for_window. maybe for example:
`for_window [Criteria] on_focus_exec "command1" on_unfocus_exec "command2"`

I know this can be done with sway-ipc and swaymsg but not everyone has the knowledge and experience to write a script

**Comment by WillPower3309** [comment]
Generally we don't accept issues that can be done through sway-ipc, however if this gets more traction I'd consider adding it

**Comment by WillPower3309** [comment]
It could be worth making a program that uses sway ipc that  execute user supplied commands when certain windows are closed / opened. Could be a good project that could see some use in the community
