### ISSUE TITLE
Won't build with GCC 12.2.0

### ISSUE THREAD

**Issue by Vulldozer** [WillPower3309/swayfx#75]
### Please fill out the following:
- **Swayfx Version: 0.1 (and also latest)**

- **Description:**
  - New warnings were introduced with newer gcc versions. in default_options `werror` is set to `true` (meson.build line 10). this means warning are treated as errors as such trying to build swayfx will fail.

  - You can still compile swayfx anyway by simply switching `werror` to `false`, but it will be more productive to address the compiler warnings.

**Comment by WillPower3309** [comment]
Thanks for raising the issue, I've addressed it by my reaction a while ago but just want to confirm by commenting that this will be fixed soon

**Comment by WillPower3309** [comment]
fixes upstream
