### ISSUE TITLE
Package for NixOS repos

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#79]
We should allow NixOS users to install swayfx, especially considering we make use of a `flake.nix` in this repo!

**Comment by WillPower3309** [comment]
@JavaCafe01 I know you had expressed interest in making a PR to nixpkgs in the past, is this still something that's on your plate? If not I can make a PR!

**Comment by WillPower3309** [comment]
Removing from 0.2 milestone as we would want to package v 0.2

**Comment by rafaelsgirao** [comment]
Is this being worked on? I'd be glad to (try to) go through with this, if not.

**Comment by WillPower3309** [comment]
> Is this being worked on? I'd be glad to (try to) go through with this, if not.

Please do! I opened this issue mostly just to track the status, I had planned on having a stab at it in the future

**Comment by WillPower3309** [comment]
Relevant: https://github.com/NixOS/nixpkgs/issues/222630

Could take a look at how i3-gaps compares to i3 and structure ours similarly to sway

**Comment by RicArch97** [comment]
PR here: https://github.com/NixOS/nixpkgs/pull/226043
