### ISSUE TITLE
AUR package states wlroots 1.15 as a dependency

### ISSUE THREAD

**Issue by head-gardener** [WillPower3309/swayfx#85]
Currently `yay -S swayfx-git` fails due to dependency being outdated. Package compiles fine with wlroots 1.16 as per my experience.

**Comment by WillPower3309** [comment]
Hmm, seems like the github action for updating the AUR package didn't run, manually running now! Should be fine once it's run as we rebased off of sway 1.8

**Comment by head-gardener** [comment]
All's good. Thanks for the quick reply.

**Comment by ErikReider** [comment]
The non -git PKGBUILD is broken aswell. Forgot to change the wlroots dependency back to 0.15 after we decided to wait on releasing 0.2. I'll create a quick pr
