### ISSUE TITLE
Option to only round edge corners in tabbed layout 

### ISSUE THREAD

**Issue by Vulldozer** [WillPower3309/swayfx#92]
- **Description:**
Only render rounded corners on the two tabs on the right and left edge.
Could be toggled on or off with a config option.

Mock-up:
 
Off (How it looks like right now):
![tabbed-layout](https://user-images.githubusercontent.com/59207724/211752311-af5bb401-22e4-47d7-9d79-a476ec461928.png)

On (How it would look like if you toggle it on):
![tabbed-layout-onlyedgecorners](https://user-images.githubusercontent.com/59207724/211752438-48d121ee-87d3-4a2b-a53a-bd7282bf2eef.png)

**Comment by ErikReider** [comment]
Fixed by #90

**Comment by Vulldozer** [comment]
Did not notice that, closing as finished
