### ISSUE TITLE
Box shadow stencil doesn't align with the bottom of floating windows

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#96]
While a window is floating, the gl stencil seems to be too large by about 1 pixel on the bottom edge of the window, below the border.

![2023-01-18_01-01-1674024689](https://user-images.githubusercontent.com/13266308/213104149-1de397f7-d542-46e3-8b25-a4cec31e8ebb.jpg)

Have tested and have been unable to reproduce for tiling windows. This issue impacts windows regardless of whether or not they have a border.

**Comment by WillPower3309** [comment]
pinging @ErikReider for visibility

**Comment by ErikReider** [comment]
Hmm. Seems to be dependent on the Y position of the window. It disappears if you move the window down or up by 1px.

Seems like it doesn't just affect the stencil...:
![image](https://user-images.githubusercontent.com/35975961/213153864-b7fd0dd9-85b9-4713-bc65-987d0da22956.png)

**Comment by ErikReider** [comment]
Maybe a rounding error?

**Comment by WillPower3309** [comment]
> Hmm. Seems to be dependent on the Y position of the window. It disappears if you move the window down or up by 1px.
> 
> Seems like it doesn't just affect the stencil...:
> ![image](https://user-images.githubusercontent.com/35975961/213153864-b7fd0dd9-85b9-4713-bc65-987d0da22956.png)
> 

Do you recall the border / corner radius / dpi in this screenshot? I'd like to reproduce the corners also being 1px off

**Comment by WillPower3309** [comment]
fixed in https://github.com/WillPower3309/swayfx/commit/e9781805a74add9bcc7de472c704a476c41c18a5

**Comment by WillPower3309** [comment]
@ErikReider mind retesting now? I'm cautious of your unaligned bottom corners

**Comment by ErikReider** [comment]
![image](https://user-images.githubusercontent.com/35975961/219905078-143ed3fc-733d-477b-8940-3dcf4bdfd64b.png)

Should just be able to remove those floors :)

**Comment by WillPower3309** [comment]
> ![image](https://user-images.githubusercontent.com/35975961/219905078-143ed3fc-733d-477b-8940-3dcf4bdfd64b.png)
> 
> Should just be able to remove those floors :)

Shoot. I think we actually need the floors for x and y values because I believe they define the top left position, I'll look into it

**Comment by WillPower3309** [comment]
Mind providing the config settings you're using as well as dpi / resolution so I can try to reproduce? @ErikReider

**Comment by ErikReider** [comment]
> Mind providing the config settings you're using as well as dpi / resolution so I can try to reproduce? @ErikReider

I was running sway in nested mode on my 1440p 27" monitor with 1x scale. Not every position displays the bug, so I usually have to move the window pixel by pixel... Setting a larger border size makes it easier to detect so moving pixel by pixel isn't usually needed.

I'm using a border size of 3px. Don't judge my messy testing config in the screenshot...

![image](https://user-images.githubusercontent.com/35975961/219947929-077c2f61-af5c-4b86-924d-2af763ccefb2.png)

**Comment by ErikReider** [comment]
I've noticed that it's easier to reproduce if you place the window border between my main monitor and my left monitor.

The black line is where my monitors meet. Hopefully the transparent, red line is visible between the left border and the kitty window

![image](https://user-images.githubusercontent.com/35975961/219960371-bd9b01d2-56f5-406e-9f2f-7f4e1932c0fb.png)

**Comment by WillPower3309** [comment]
> I've noticed that it's easier to reproduce if you place the window border between my main monitor and my left monitor.
> 
> The black line is where my monitors meet. Hopefully the transparent, red line is visible between the left border and the kitty window
> 
> ![image](https://user-images.githubusercontent.com/35975961/219960371-bd9b01d2-56f5-406e-9f2f-7f4e1932c0fb.png)
> 

Oof, I had been hoping it would have been a lack of floor() on the x and y position of the bottom border, but it being present on the left side border negates that.

**Comment by WillPower3309** [comment]
Border issue tracked in #113
