### ISSUE TITLE
Add shadow_offset command

### ISSUE THREAD

**Issue by WillPower3309** [WillPower3309/swayfx#99]
We should support having a shadow offset. This would mean that the shadow is shifted down and to the left by the specified value. Alternatively, if the value is negative, the shadow would be shifted up and to the right.

**Comment by WillPower3309** [comment]
I'm not pikcy on the naming of the config option or the syntax, the above is just a suggestion

**Comment by ErikReider** [comment]
The suggested config syntax sounds good to me. Maybe a `shadow_offset x y`?
